Lecture10
yamamoto-18/RaiseTech pull request #9
Opened 2024-02-14 12:17 UTC by yamamoto-18

第10回授業課題を作成致しました。
ご確認の程宜しくお願い致します。

2024-02-14 14:21 UTC, MasatoshiMizumoto requested changes
提出ありがとうございます！
以下ご対応お願いします！！

- テンプレートファイル
  - ファイル終端の警告あり
- Outputs名称
  - 名称からどのような構造情報かもわかるのが理想（Id、List、Numberなど）

2024-02-14 15:19 UTC, yamamoto-18 commented
> 提出ありがとうございます！ 以下ご対応お願いします！！
> 
> * テンプレートファイル
>   
>   * ファイル終端の警告あり
> * Outputs名称
>   
>   * 名称からどのような構造情報かもわかるのが理想（Id、List、Numberなど）

2024-02-14 15:23 UTC, yamamoto-18 commented
修正致しました。
恐れ入りますが再度ご確認をお願い致します。
（間違えて一度Close with commentを押してしまいました…）

2024-02-15 00:44 UTC, MasatoshiMizumoto approved these changes
LGTMです！
1点お伝えしておきますが、Outputs名はRef以外の情報（GetAttなど）も格納できるので、必ずIDが格納されるとは限りません。
すべてのOutputs名称はどのような属性の情報が格納されるのかわかる命名規則にしておくと一目置かれるかなと思いました！

課題としてはOKです！お疲れさまでした！

2024-02-15 00:59 UTC, yamamoto-18 commented
ご確認ありがとうございます！
Outputsにどういったものが格納できるかおおまかに理解しているつもりでしたが、もっと具体的にどういったものが格納できるのかまで調べられておりませんでした！
再度調べてみようと思います！ありがとうございます！

2024-02-15 02:12 UTC, merged